### PR TITLE
I added a post related comedy and story telling for presentations and…

### PR DESCRIPTION
**Pull request by yoshuadiaz**
## DESCRIPTION
I added a post to teach about how to enhance speeches and presentations with storytelling and humor

## INFORMATION
The post offers recommendations, tips and materials for enhance your spech with identification tools and a quick humor tips

```yaml
name:
username: https://platzi.com/@<USERNAME>
coach:
```

## PR TYPE

- [x] BlogPost
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement

### CODE REVIEW

**Comment by gndx** [comment]
@yoshuadiaz La descripción no incluye la información solicitada.

**Comment by yoshuadiaz** [comment]
> @yoshuadiaz La descripción no incluye la información solicitada.

Ups, me podrías indicar lo que me faltó o como escribirlo para tenerlo bien en mente? :)

**Comment by gndx** [comment]
INFORMATION
The post offers recommendations, tips and materials

name:
username: https://platzi.com/@<USERNAME>
coach:

**Comment by yoshuadiaz** [comment]
> INFORMATION
> The post offers recommendations, tips and materials
> 
> name:
> username: https://platzi.com/@
> coach:

actualicé el pullrequest :)

**Review by gndx — APPROVED** [review]

**Pull request merged**
